### ISSUE TITLE
Проблемы с воспроизведением видео

### ISSUE THREAD

**Issue by AlexanderShad** [Etersoft/XimperLinux#1]
**Описание ошибки**

1) Периодически пропадает звук. Включаешь видео к примеру через celluloid видео идет, звука нет.  В системе звук включен, в приложении звук включен.. Открываешь видео в VLC он пишет чтоб звук mute, отсчелкиваешь делаешь громче и звук есть. Переоткрываешь в celluloid тоже все нормально. Непонятно почему в системе пропадает звук. 

2) Проглючивание при просмотре видео. Открываешь смотришь.. начинаешь туда сюда мотать, либо пауза продолжить несколько раз.. и рандомно происходит сброс видео. Т.е. плеер висит, но видео как бы закрывается... нажимаешь пробел оно начинается сначала... Изначально думал, что глюк Celluliod, но после скачивания VLC-maxi такое же поведение.. Происходит рандомно, когда при перемотах, когда при паузе

**Воспроизведение**

выше описал

**Ожидаемое поведение**

Четкое и сжатое описание того, что вы ожидали увидеть.

**Скриншоты**

про звук https://disk.yandex.ru/i/-oz7WOvkAkeMbA

**Операционная система (пожалуйста, обязательно заполните следующую информацию):**

 - Версия образа (например: 'gnome nvidia 0.9' или 'gnome 0.9.1')
 апдейтился с 0.7, сейчас 0.9.1

 - Вывод команды 'epm print info'

[aleksandr@ximper ~]$ epm print info
distro_info v20230406 (EPM version 3.60.4-alt1) : Copyright © 2007-2023 Etersoft

                       Pretty name (--pretty): Ximper Linux 0.9.1 (Alice) (Sisyphus)
           (--distro-name / --distro-version): Etersoft Ximper / 0.9.1 (orig. Etersoft Ximper 0.7.7)
         Base distro name (-d) / version (-v): ALTLinux/Sisyphus
     Vendor distro name (-s) / Repo name (-r): alt / Sisyphus
                 Package manager/type (-g/-p): apt-rpm / rpm
            Base OS name (-o) / CPU arch (-a): linux x86_64
                 CPU norm register size  (-b): 64 bit
                          Virtualization (-i): (host system)
                        CPU Cores/MHz (-c/-z): 8 / 1309 MHz
                      System memory size (-m): 6873 MiB
                 Running service manager (-y): systemd
            Bug report URL (--bug-report-url): https://bugs.altlinux.org/

(run with -h to get help)

**Дополнительная информация**

нет

**Comment by X1mper** [comment]
Воспроизводится ли это на свежеустановленном образе 0.9?

**Comment by AlexanderShad** [comment]
> Воспроизводится ли это на свежеустановленном образе 0.9?

Здравствуйте,
Лично я не готов ответить на Ваш вопрос, так как планов переустанавливать систему у меня пока нет.
На данный момент прочитал про и доустановил пакет firmware-alsa-sof, пока пропадание звука не воспроизводилось (ошибка 1) возможно совпадение, по сбросу видео пока не готов сказать, надо посмотреть еще.
С уважением

**Comment by X1mper** [comment]
> > Воспроизводится ли это на свежеустановленном образе 0.9?
> доустановил пакет firmware-alsa-sof, пока пропадание звука не воспроизводилось

Если ошибка не вернется (например, в течении недели) добавим этот пакет в дистрибутив

**Comment by AlexanderShad** [comment]
> Если ошибка не вернется (например, в течении недели) добавим этот пакет в дистрибутив

Я понял, я отпишусь Вам

**Comment by AlexanderShad** [comment]
> Если ошибка не вернется (например, в течении недели) добавим этот пакет в дистрибутив

Отваливание видео пока не повторялось, но заглушение звука повторилось. Следовательно не в пакете дело. При открытии регулятора громкости, видно что звук в системе есть, если открыть консоль и там потыкать вверх вниз системный звук есть... но заглушен звук в проигрывателе celluloid, он выключен там, хотя в самом проигрывателе написано что звук включен на полную. Я неделю попробую поюзать vlc, если проблема не воспроизведется... то напишу баг в багзиру Альта Сизива на пакет celluloid  , если воспроизведется, тогда не знаю что случилось...

**Comment by X1mper** [comment]
К слову, в ксимпер 0.9 предустановлен MPV в качестве основного видеопроигрывателя. Попробуйте еще и его.

**Comment by AlexanderShad** [comment]
Доброго времени суток. 
Я понял. Сделал 
$ epmi mpv
Потестирую на нем, вместо vlc, потом Вам отпишусь

**Comment by AlexanderShad** [comment]
Кстати, по MPV.. я вспомнил почему отказался от него...
он протормаживает при просмотре видео 4к, то есть видео идет когда нормально, а когда заметно с тормазами, при этом только картинка, звук не тормозит. Багу сегодня в багзилу повешаю
хар-ки видео:
контейнер - Quicktime
размеры - 3840 × 1608
видеокодек - H.265 (Main Profile)
битрейт видео - 7570 кбит/с
частота кадров - 25,00 кадров в секунду
аудиокодек - MPEG-4 AAC
битрейд - 125 кбит/с
частота - 48000 Гц

**Comment by AlexanderShad** [comment]
Доброго времени суток!
В общем резюмирую...
После установки пакет firmware-alsa-sof и регулярных обновлениям сброс видео при паузах перемотках больше не воспроизводился, тестил на mpv.

Заглушение звука воспроизвелось, использовал MPV. 
То есть отключение звука воспроизвелось на mpv на culluliod на vlc.
Фактически при открытие регулятора громкости, при заглушенном звуке видно что звук в системе есть, он реально работает (к примеру в консоли потыкать вверх вниз, то звенит), а на видео проигрывателе стоит как бы нажатая Загрушить звук и бегунок выкручен в Тишина. При этом в mpv возле иконки включенная громкость стоит восклицательный знак.
В регуляторе громкости отсчелкиваешь заглушить звук, выкручиваешь бегунок и звук появляется. И это происходит именно в видео проигрывателях (приложениях)... браузеры что-то не додумался сразу посмотреть при такой ситуации.
В общем крутил вертел, я так и не понял почему это происходит, были предположения, но не подтвердились, не воспроизвелось отключение звука. 
В alsamixer при выборе устройства в auto-mute стоит disabled

В общем не знаю я с чем это связано... 
По тормозам mpv при 4к я багу повешал.

Переустанавливать систему не планирую. По этому к сожалению идей у меня нет ) Ну хоть сброс видео вроде как ушел )

**Comment by X1mper** [comment]
Исправляют ли проблему эти команды?:
```
sudo systemctl --global disable pipewire
sudo systemctl --global disable wireplumber
systemctl --user enable pipewire
systemctl --user enable wireplumber
```

**Comment by AlexanderShad** [comment]
Добрый день!
Как и говорил выше, сброс видео при паузах перемотках больше не воспроизводится, использую mpv.

Команды выполнил.
Посмотрю несколько дней будет ли воспроизводится заглушение звука или нет, по результату Вам отпишусь.

**Comment by X1mper** [comment]
> Команды выполнил. Посмотрю несколько дней будет ли воспроизводится заглушение звука или нет, по результату Вам отпишусь.

Да-да. это про сброс звука :)

**Comment by AlexanderShad** [comment]
Добрый день!
Проблема с отключением звука в приложениях воспроизвелась.
Сессия wayland
скрин как это выглядит в управлении громкостью
https://disk.yandex.ru/i/aA199iAkmm-s8A
В браузере в ютуб тоже звук был зачеркнут.. ну я там нажал отчеркнуть и он появился но только в браузере.. запустил mpv как не было так и нет )))
странная ситуация )) 
ну да ладно... я уже привык ))

**Comment by X1mper** [comment]
> Добрый день! Проблема с отключением звука в приложениях воспроизвелась. Сессия wayland скрин как это выглядит в управлении громкостью https://disk.yandex.ru/i/aA199iAkmm-s8A В браузере в ютуб тоже звук был зачеркнут.. ну я там нажал отчеркнуть и он появился но только в браузере.. запустил mpv как не было так и нет ))) странная ситуация )) ну да ладно... я уже привык ))

Печально, но я хотя-бы пытался :(

**Comment by AlexanderShad** [comment]
Спасибо Вам.
Да и я не против пытаться это исправить :)
у меня просто нет идей в какую сторону капать... учитывая что данная проблема возникает периодически, а не стабильно.
Если я что накопаю, я обязательно Вам сюда напишу.
