### ISSUE TITLE
Не запоминает "Другие расположения" при переключении сессий x11 на wayland

### ISSUE THREAD

**Issue by AlexanderShad** [Etersoft/XimperLinux#2]
**Описание ошибки**

При создании в nautilus в "Другие расположения" соединения davs под сессией Gnome на X.org (x11) и потом перехода в Gnome (wayland) соединение в "Другие расположения" пропадает.
Если выбрать из "Недавние серверы" (оно там есть) и подключиться то все соединяется ок, появляется в "Другие расположения - Сети", но после размонтирования исчезает из списка.

**Скриншоты**

https://disk.yandex.ru/d/TQLSg5rO8br2kQ

**Операционная система (пожалуйста, обязательно заполните следующую информацию):**

$ epm print info
distro_info v20230406 (EPM version 3.60.5-alt1) : Copyright © 2007-2023 Etersoft

                       Pretty name (--pretty): Ximper Linux 0.9.1 (Alice) (Sisyphus)
           (--distro-name / --distro-version): Etersoft Ximper / 0.9.1 (orig. Etersoft Ximper 0.7.7)
         Base distro name (-d) / version (-v): ALTLinux/Sisyphus
     Vendor distro name (-s) / Repo name (-r): alt / Sisyphus
                 Package manager/type (-g/-p): apt-rpm / rpm
            Base OS name (-o) / CPU arch (-a): linux x86_64
                 CPU norm register size  (-b): 64 bit
                          Virtualization (-i): (host system)
                        CPU Cores/MHz (-c/-z): 8 / 1450 MHz
                      System memory size (-m): 6873 MiB
                 Running service manager (-y): systemd
            Bug report URL (--bug-report-url): https://bugs.altlinux.org/

**Comment by X1mper** [comment]
Проверю

**Comment by X1mper** [comment]
А есть смысл переходить между режимами?

**Comment by AlexanderShad** [comment]
Да думаю можно закрыть данный issue
