### ISSUE TITLE
Предложение по настройкам MPV для wayland

### ISSUE THREAD

**Issue by AlexanderShad** [Etersoft/XimperLinux#3]
**Проблемы, которые бы решились после выполнения предложения**
Предлагаю донастроить mpv, хотя возможно Вы это уже сделали :)

** вывод epm print info **
$ epm print info
distro_info v20230406 (EPM version 3.60.5-alt1) : Copyright © 2007-2023 Etersoft

                       Pretty name (--pretty): Ximper Linux 0.9.1 (Alice) (Sisyphus)
           (--distro-name / --distro-version): Etersoft Ximper / 0.9.1 (orig. Etersoft Ximper 0.7.7)
         Base distro name (-d) / version (-v): ALTLinux/Sisyphus
     Vendor distro name (-s) / Repo name (-r): alt / Sisyphus
                 Package manager/type (-g/-p): apt-rpm / rpm
            Base OS name (-o) / CPU arch (-a): linux x86_64
                 CPU norm register size  (-b): 64 bit
                          Virtualization (-i): (host system)
                        CPU Cores/MHz (-c/-z): 8 / 1477 MHz
                      System memory size (-m): 6873 MiB
                 Running service manager (-y): systemd
            Bug report URL (--bug-report-url): https://bugs.altlinux.org/

**Варианты на рассмотрение**
На своем ноутбуке я столкнулся с двумя проблемами с проигрывателем MPV
1. Тормоза при просмотре 4К видео
2.  Затухание и выключение экрана при включенных настройках питания "Уменьшения яркости экрана" и "Выключение экрана"

Учитывая, что MPV используется по умолчания в дистрибутиве и я не знаю какие там настройки у Вас ) 
Предлагаю рассмотреть мои предложения по пунктам

1. в ~/.config/mpv/mpv.conf 
hwdec=vaapi
vo=dmabuf-wayland
save-position-on-quit
resume-playback-check-mtime
stop-screensaver
включить аппаратное ускорение (для 4к) и я еще добавил stop-screensaver ... хотя для вайлан на отключение экрана он никак не влияет... как я понял это больше по х11

2. В файле /usr/share/applications/mpv.desktop после Exec= перед mpv  вставить gnome-session-inhibit 
Exec=gnome-session-inhibit mpv --player-operation-mode=pseudo-gui -- %U

это решит проблему с потухание экрана при просмотре видео на вайлан сессии

ниже багрепорты по этим вопросам
1. https://bugzilla.altlinux.org/48887
2. https://bugzilla.altlinux.org/49008

С уважением

**Comment by AlexanderShad** [comment]
Кстати, в вики арч линукса нашел ссылку на скрипт который вроде как решает вопрос с затухание экрана
Но работоспособность не проверял
https://gist.github.com/crazygolem/a7d3a2d3c0cee5d072c0cbbbdee69286

**Comment by AlexanderShad** [comment]
Было бы классно если бы из коробки данный вопрос решался )
Но опять же, повторюсь, может Вы уже все сделали, эт просто я со старой версии еду :)

**Comment by X1mper** [comment]
Не все сидят на wayland... Сломается-ли что-то на иксак при такой настройке - пока не понятно... 
Лучше бы это продвинуть в апстрим (сизиф либо самого MPV)

**Comment by AlexanderShad** [comment]
Ну тоже верно. 
Тогда может быть добавить в сборку пакет gnome-shell-extension-caffeine который априори должен решить проблему с потуханием mpv на wayland, учитывая что данный проигрыватель по умолчанию. А устанавливать пакет gnome-shell-extension-caffeine предлагаю при установки системы, если выбран mpv, если не выбран, то можно не ставить.
Ну как вариант )

**Comment by X1mper** [comment]
Про кофеин подумаю
