### ISSUE TITLE
Предлагаю включить пакет libwebp-pixbuf-loader в состав дистрибутива

### ISSUE THREAD

**Issue by AlexanderShad** [Etersoft/XimperLinux#4]
Добрый день!

Предлагаю включить пакет libwebp-pixbuf-loader в состав дистрибутива
После установки появилась возможность пред просматривать изображения формата *.webp в наутилусе, а тек же Глаз Гном стал открывать эти изображения

**Comment by X1mper** [comment]
Проверим и добавим. Спасибо!

**Comment by X1mper** [comment]
Будет в 0.9.1+
