### ISSUE TITLE
Повисание внешнего монитора при возникновении ошибки обращения к службам ОС 

### ISSUE THREAD

**Issue by aosivt** [Etersoft/XimperLinux#5]
**Описание ошибки**

Монитор перестает обновлять картинку (повисает/фризится) при открытии файлового менеджера. 
Из лога выяснил что не было доступа к папке /var/lib/samba/usershares/
**Воспроизведение**

Шаги для воспроизведения:
1. Вызвать открытие Nautils через super+f
2. Внешний монитор либо на время повисает или окончательно пока не перезапустишь ОС 

**Ожидаемое поведение**

Внешний монитор не повисает

Добавьте скриншоты, которые помогут объяснить вашу проблему.

**Операционная система (пожалуйста, обязательно заполните следующую информацию):**

 - Версия образа (например: 'gnome nvidia 0.9' или 'gnome 0.9.1') gnome nvidia 0.9
 - Вывод команды 'epm print info'
distro_info v20230406 (EPM version 3.60.5-alt1) : Copyright © 2007-2023 Etersoft

                       Pretty name (--pretty): Ximper Linux 0.9.1 (Alice) (Sisyphus)
           (--distro-name / --distro-version): Etersoft Ximper / 0.9.1 (orig. Etersoft Ximper 0.9)
         Base distro name (-d) / version (-v): ALTLinux/Sisyphus
     Vendor distro name (-s) / Repo name (-r): alt / Sisyphus
                 Package manager/type (-g/-p): apt-rpm / rpm
            Base OS name (-o) / CPU arch (-a): linux x86_64
                 CPU norm register size  (-b): 64 bit
                          Virtualization (-i): (host system)
                        CPU Cores/MHz (-c/-z): 20 / 399 MHz
                      System memory size (-m): 64012 MiB
                 Running service manager (-y): systemd
            Bug report URL (--bug-report-url): https://bugs.altlinux.org/

**Comment by aosivt** [comment]
Нашел временное решение которое поспособствует разлипанию:
1. Дописать в настройки grub в строке GRUB_CMDLINE_LINUX_DEFAULT параметр intel_idle.max_cstate=1
2. Так же дописать параметры i915.enable_psr=0 i915.enable_fbc=0 i915.modset=0"
после вставки параметров произвести обновление grub
```bash
sudo update-grub
```

и перезапустить машину

П.С.
1. п указывает на ограничение состояния сна, но это приводит к увеличению электропотребления
2. п указывает на отключение фиксации последнего кадра на мониторе (с этим параметром вроде как производиться меньше обращений к ОЗУ), но приводить к повисанию изображения на мониторе.
П.П.С.
Это временное решение, и оно может не подойти всем.

**Comment by aosivt** [comment]
На всякий случай, мне помогло переход на wayland
Переход осуществлял:
1. Добавление в файл /etc/default/grub в строку содержащую GRUB_CMDLINE_LINUX_DEFAULT в параметры ```nvidia-drm.modeset=1```
2. выполнение в терминале ```sudo ln -s /dev/null /etc/udev/rules.d/61-gdm.rules```
3. Обновление grub ```sudo update-grub```
4. Перезапуск машины
Но появились косяки с отображением раскладки. Проверяю дальше.

**Comment by X1mper** [comment]
> На всякий случай, мне помогло переход на wayland Переход осуществлял:
> 
> 1. Добавление в файл /etc/default/grub в строку содержащую GRUB_CMDLINE_LINUX_DEFAULT в параметры `nvidia-drm.modeset=1`
> 2. выполнение в терминале `sudo ln -s /dev/null /etc/udev/rules.d/61-gdm.rules`
> 3. Обновление grub `sudo update-grub`
> 4. Перезапуск машины
>    Но появились косяки с отображением раскладки. Проверяю дальше.

Сделано в 0.9.1
