### ISSUE TITLE
Предлагаю рассмотреть добавление пакетов sane-airscan и simple-scan

### ISSUE THREAD

**Issue by AlexanderShad** [Etersoft/XimperLinux#6]
Добрый день!

Предлагаю рассмотреть возможность добавления в дистрибутив пакетов sane-airscan и simple-scan, чтоб из коробки была поддержка сетевых сканеров и простоя программка для сканирования.

Ну или хотя б пакет поддержки сетевых сканеров, а уж чем сканировать пользователь сам выберет.

С уважением

**Comment by X1mper** [comment]
возможно будет в 0.9.1 отдельной галочкой

**Comment by X1mper** [comment]
Будет в 0.9.2

**Comment by X1mper** [comment]
В 0.9.3 точно будет :)

**Comment by X1mper** [comment]
https://gitlab.eterfund.ru/ximperlinux/mkimage-profiles/commit/059f2b81b44c57a9c118bea730335f50cca01cc3
Добавлено :)
