### ISSUE TITLE
Готовые образы/сборки/пакеты приложений Windows для запуска

### ISSUE THREAD

**Issue by yudinmaxim** [Etersoft/XimperLinux#9]
Как пример решения: snap пакет Fusion 360 (сейчас он не устанавливается - ломается на этапе установки EDGE, но ранее работал нормально).
Это snap пакет, который настраивает wine, скачивает дистриб Fusion 360 и устанавливает его так, чтобы тот точно работал.

В какой-то степени за аналогичный функционал можно принять wine_install_kompass от команды разработки etersoft@wine. Но, к примеру, у меня скрипт не отработал.

Это не единичные примеры программ.

Например: популярный пакет офисных программ WPS Office, хоть и имеет версию под Линукс - она обрезанная и не обеспечивает полным функционалом - её версия для Windows довольно успешно работает под wine.

Если брать в расчет ситуацию с мультимедиа-программами - то там и аналогов практически нет.
Например программный продукт GuitarRig.

Как я вижу решение:
готовые snap, flatpack (или ещё какие-нибудь) пакеты, которые устанавливаются как любой другой пакет, но при этом тянут за собой настроенную версию wine с нужными зависимостями, всё ставят и настраивают так, что для конечного пользователя всё выглядит как обычная установка. А под капотом программа работает на основе wine.

**Comment by X1mper** [comment]
Такое уже реализовано в epm play.
В любом случае, мы преимущественно за использование нативных для Линукс программ.
Впс офис же, как по мне, не урезан. Если вы можете конкретно сказать, в чем он урезан по сравнению с виндовс версией, напишите.
